# Harmonics - Unified Mod (Weapons + Instruments + Armor) for NeoForge
license="${mod_license}"

[[mods]] #mandatory

# The modid of the mod
modId="${mod_id}" #mandatory

# The version number of the mod
version="${mod_version}" #mandatory

# A display name for the mod
displayName="${mod_name} (Unified)" #mandatory

# A short description of the mod
description='''
Harmonics enriches your Minecraft experience with a massive collection of music, combat, and defense options! Explore over 130 unique items, including 36 weapons, 50 playable instruments, and 44 complete armor sets crafted from various vanilla and custom materials.
'''

# An icon file that will be shown in the Mods list
iconFile="harmonics_logo.png"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"