org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# Environment
minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.48-beta

# Mod Properties
mod_id=harmonics
mod_name=Harmonics
mod_license=All Rights Reserved
mod_version=1.6.2
mod_group_id=com.antonius